language: node_js
node_js:
  - 18
services:
  - redis-server
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl restart postgresql@11-main
  - sleep 1
before_script:
  - cp sites/public/.env.template sites/public/.env
  - cp sites/partners/.env.template sites/partners/.env
  - cp backend/core/.env.template backend/core/.env
jobs:
  include:
    - script: yarn build:app:public
      name: Build public site
    - script: yarn build:app:partners
      name: Build partners site
    - script: yarn test:backend:core:testdbsetup && yarn test:backend:core
      name: Backend unit tests
    - script: yarn test:e2e:backend:core
      name: Backend e2e tests
    - script: yarn test:app:public:unit
      name: Public site unit tests
    - script: yarn test:app:partners:unit
      name: Partners site unit tests
    - stage: longer tests
      name: Partners site Cypress tests
      script:
        - yarn cypress install
        - cd backend/core
        - yarn db:reseed:detroit
        - yarn nest start &
        - cd ../../sites/partners
        - yarn build
        - yarn start -p 3001 &
        - yarn wait-on "http-get://localhost:3001" && yarn cypress run
        - kill $(jobs -p) || true
    - stage: longer tests
      name: Public site Cypress tests
      script:
        - yarn cypress install
        - yarn db:reseed
        - cd backend/core
        - yarn nest start &
        - cd ../../sites/public
        - yarn build
        - yarn start -p 3000 &
        - yarn wait-on "http-get://localhost:3000" && yarn cypress run
        - kill $(jobs -p) || true
dist: focal
addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
      - libgconf-2-4
env:
  global: PGPORT=5433
    PGUSER=travis
    TEST_DATABASE_URL=postgres://localhost:5433/bloom_test
    REDIS_TLS_URL=redis://127.0.0.1:6379/0
    NEW_RELIC_ENABLED=false
    NEW_RELIC_LOG_ENABLED=false
