language: node_js

node_js:
  # Node version
  - 12

cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache

services:
  - redis-server

before_install:
  # Trust all local connections to postgres, due to not being able to authenticate as the travis user.
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl restart postgresql@11-main
  - sleep 1

before_script:
  - cp sites/public/.env.template sites/public/.env
  - cp sites/partners/.env.template sites/partners/.env
  - cp backend/core/.env.template backend/core/.env

defaults: &defaults
  script:
    - yarn db:reseed
    - cd backend/core
    # start backend/core in the background
    - yarn nest start &
    - cd ../../sites/public
    - yarn dev &
    - yarn wait-on "http-get://localhost:3000" && yarn cypress run -- --record --parallel --group "$STAGE_NAME"
    # after all tests finish running we need to kill all bg jobs
    - kill $(jobs -p) || true

jobs:
  include:
    - script: yarn test:shared:ui
      name: "UI components tests"
    - script: yarn build:app:public
      name: "Build public site"
    - script: yarn build:app:partners
      name: "Build partners site"
    - script: yarn test:shared:ui:a11y
      name: "Storybook a11y testing"
    - script: yarn test:backend:core:testdbsetup && yarn test:backend:core
      name: "Backend unit tests"
    - name: "Cypress 1"
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - name: "Cypress 2"
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - name: "Cypress 3"
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - name: "Cypress 4"
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
      # if using Ubuntu 16 need this library
      # # https://github.com/cypress-io/cypress-documentation/pull/1647
      - libgconf-2-4

env:
  global: PGPORT=5433
    PGUSER=travis
    TEST_DATABASE_URL=postgres://localhost:5433/bloom_test
    REDIS_TLS_URL=redis://127.0.0.1:6379/0
