language: node_js

node_js:
  # Node version
  - 12

cache:
  yarn: true

services:
  - redis-server

before_install:
  # Trust all local connections to postgres, due to not being able to authenticate as the travis user.
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl restart postgresql@11-main
  - sleep 1

before_script:
  - cp sites/public/.env.template sites/public/.env
  - cp sites/partners/.env.template sites/partners/.env
  - cp backend/core/.env.template backend/core/.env
  - yarn install:all

jobs:
  include:
    - script: yarn test:shared:ui
      name: "UI components tests"
    - script: yarn build:app:public
      name: "Build public site"
    - script: yarn build:app:partners
      name: "Build partners site"
    - script: yarn test:shared:ui:a11y
      name: "Storybook a11y testing"
    - script: yarn test:backend:core:testdbsetup && yarn test:backend:core
      name: "Backend unit tests"
    - script: yarn test:e2e:backend:core
      name: "Backend e2e test"

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

env:
  global: PGPORT=5433
    PGUSER=travis
    TEST_DATABASE_URL=postgres://localhost:5433/bloom_test
    REDIS_TLS_URL=redis://127.0.0.1:6379/0
