language: node_js

node_js:
  # Node version
  - 12

services:
  - redis-server
  - postgresql

before_script:
  - yarn install:all

jobs:
  include:
    - script: yarn test:shared:ui
      name: "UI components tests"
    - script: yarn build:app:public
      name: "Build public site"
    - script: yarn build:app:partners
      name: "Build partners site"
    - script: yarn test:backend:core:testdbsetup && yarn test:backend:core
      name: "Backend unit tests"

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11

env:
  global:
    PGPORT=5433
    PGUSER=travis
    TEST_DATABASE_URL=postgres://localhost:5433/bloom_test
