language: node_js

node_js:
  # Node version
  - 12

services:
  - redis-server

before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart 12
  - sleep 1

before_script:
  - yarn install:all

jobs:
  include:
    - script: yarn test:shared:ui
      name: "UI components tests"
    - script: yarn build:app:public
      name: "Build public site"
    - script: yarn build:app:partners
      name: "Build partners site"
    - script: yarn test:backend:core:testdbsetup && yarn test:backend:core
      name: "Backend unit tests"

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

env:
  global:
    PGPORT=5433
    TEST_DATABASE_URL=postgres://localhost:5433/bloom_test
