version: '3.4'

services:
  bloomhousingpublic:
    image: bloomhousingpublic
    build:
      context: sites/public
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
