version: '3.4'

services:
  bloomhousingpublic:
    build:
      context: ./sites/public
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./sites/public:/app/sites/public
      - /app/sites/public/node_modules