export const user = {
  agreedToTermsOfService: false,
  confirmedAt: new Date(),
  createdAt: new Date("2022-09-04T17:13:31.513Z"),
  dob: new Date(),
  email: "first.last@bloom.com",
  failedLoginAttemptsCount: 0,
  firstName: "First",
  hitConfirmationURL: null,
  id: "user_1",
  jurisdictions: [
    { id: "e50e64bc-4bc8-4cef-a4d1-1812add9981b" },
    { id: "d6b652a0-9947-418a-b69b-cd72028ed913" },
  ],
  language: null,
  lastLoginAt: new Date(),
  lastName: "Last",
  leasingAgentInListings: [],
  mfaEnabled: true,
  middleName: "Middle",
  passwordUpdatedAt: new Date(),
  passwordValidForDays: 180,
  phoneNumber: null,
  phoneNumberVerified: false,
  roles: { user: { id: "user_1" }, isAdmin: true, isJurisdictionalAdmin: false, isPartner: false },
  updatedAt: new Date(),
}
