name: Assign to One Project

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues to the Backlog project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened' && github.event.issue != null
      with:
        project: 'https://github.com/CityOfDetroit/bloom/projects/1'
        column_name: 'Needs triage'
